name:                monomer-file-dialog
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/Anteproperispomenon/monomer-file-dialog
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2025 Author name here
#category:
extra-source-files:
- README.md

default-extensions:
- DerivingStrategies
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- ImportQualifiedPost
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- OverloadedStrings
- PatternSynonyms
- ScopedTypeVariables
- TupleSections
- TypeApplications

dependencies:
  - base >= 4.7 && < 5
  - containers >= 0.5.8
  - data-default
  - directory >= 1.3.8
  - filepath
  - lens
  - monomer
  - monomer-hagrid
  - text
  - text-show
  - time

library:
  source-dirs: src
  ghc-options:
  - -fwarn-incomplete-patterns
  - -threaded

executables:
  app:
    source-dirs:      app
    main:             Main.hs
    dependencies:
      - monomer-file-dialog
    ghc-options:
    - -fwarn-incomplete-patterns
    - -threaded
