name:                monomer-file-dialog
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/Anteproperispomenon/monomer-file-dialog
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2025 Author name here
#category:
extra-source-files:
- README.md

default-extensions:
- FlexibleContexts
- FlexibleInstances
- ImportQualifiedPost
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- OverloadedStrings
- PatternSynonyms
- ScopedTypeVariables
- TupleSections
- TypeApplications

dependencies:
  - base >= 4.7 && < 5
  - containers
  - data-default
  - directory
  - filepath
  - lens
  - monomer
  - text
  - text-show

library:
  source-dirs: src
  ghc-options:
  - -fwarn-incomplete-patterns
  - -threaded

